<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Serial Number_SerialNumber</name>
   <tag></tag>
   <elementGuidId>6b335f33-92bd-4b26-8019-f6b706a25151</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SerialNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SerialNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e493c9bf-1c7d-4bad-8435-1d2db490e5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>medequip-input w-100</value>
      <webElementGuid>1f50d631-6d83-4208-90bd-13fd138233ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>5f5c3337-1366-4cf7-8bfd-540fe7b8df65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f8561d0-cb0b-40bd-b225-6c835810567e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d4e54700-e5a6-457f-a2f3-7e1f271ee82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field SerialNumber must be a string or array type with a maximum length of '50'.</value>
      <webElementGuid>e0f2cb55-673c-4f16-b622-b0f507d77e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>48f53c54-d4c1-43d0-a2f5-d87bcd93f58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Invalid SerialNumber- alphanumeric allowed.</value>
      <webElementGuid>c1cef44b-e041-4970-9e7f-9d40bcd52a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>[A-Za-z0-9]+</value>
      <webElementGuid>e6eb615c-e95b-4dd1-b972-804e18c9e5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Required field</value>
      <webElementGuid>b8bb4d72-d4b5-49c8-ae71-a005e1574fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SerialNumber</value>
      <webElementGuid>674e4d3b-afaa-4ced-9c83-736863fbc9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SerialNumber</value>
      <webElementGuid>7815a97d-6b7e-45b1-bdda-a1a8b3e9b9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SerialNumber&quot;)</value>
      <webElementGuid>cc1720bd-55b5-425a-a397-debf8c0a4fad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SerialNumber']</value>
      <webElementGuid>a697a7c5-69cc-4f42-aa5f-7cf884c6c95a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-add-entry']/div[2]/div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>10beb823-1ba3-41fc-80e6-be5417c2b319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>57b95c39-c62b-4b79-a57d-5ed0ca9e3e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'SerialNumber' and @name = 'SerialNumber']</value>
      <webElementGuid>11fd783c-f731-463f-90f9-1d7aaceb740a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
