<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Barcode_Barcode</name>
   <tag></tag>
   <elementGuidId>22881163-3036-4b34-9756-63cc440d8ebd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Barcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Barcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>308a8730-a461-4d62-8d5e-7447c89d8c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>medequip-input w-100</value>
      <webElementGuid>e6c5d68d-3f61-4aaa-853b-8548b3398c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>c844ab95-768f-445a-a926-f6cb6eaeb9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a959a15-fae0-4dd9-81b7-ffd6f5307aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e11260e8-2ff7-4ae5-9a89-0181996338d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Invalid Barcode- alphanumeric allowed.</value>
      <webElementGuid>2bb7e037-5fcc-46ee-a38d-5a1097317153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>[A-Za-z0-9]+</value>
      <webElementGuid>cf9fe395-1f15-4b1e-b170-53acf2efe91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Required field</value>
      <webElementGuid>c5ccbdb4-1b6d-45b8-ad72-6730c9a93ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Barcode</value>
      <webElementGuid>ac44ef13-bedf-48e1-abd4-7104f7081a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Barcode</value>
      <webElementGuid>228799c3-6eac-4789-a2f3-3ce5b9b4a2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Barcode&quot;)</value>
      <webElementGuid>00616808-e101-4f27-b479-8d3f23e084fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Barcode']</value>
      <webElementGuid>b24eb6c8-8413-4292-9b8a-506608686554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-add-entry']/div[2]/div[3]/div/div/div[2]/input</value>
      <webElementGuid>d690bb7b-5889-47f0-99b3-a7b9b7364a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/input</value>
      <webElementGuid>c0ca6773-769f-4fd9-b8fa-d646ff7fc3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Barcode' and @name = 'Barcode']</value>
      <webElementGuid>7fd7f725-b838-40b0-816a-6fe16cc40127</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
