<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Export_btn-create-entry</name>
   <tag></tag>
   <elementGuidId>81e4e27d-adab-448e-9414-4961ceabc889</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-create-entry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn-create-entry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54933d12-d801-4515-8e8f-92854089abb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bdd4e01e-ceac-47ba-9244-5bf1dfb51bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-create-entry</value>
      <webElementGuid>dbcc5499-d09a-4177-bbb0-19f3d749ce39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add Asset</value>
      <webElementGuid>44fe3c99-eeee-4d3b-a376-19e2beef4e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary</value>
      <webElementGuid>5889b3c7-eea1-4000-ac25-f181d9584e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>attr-add-url</name>
      <type>Main</type>
      <value>/Asset/Add</value>
      <webElementGuid>92a70008-befb-455b-af5c-a925be26ffed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-create-entry&quot;)</value>
      <webElementGuid>500e5d1b-962b-46b1-a200-974ef0971563</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn-create-entry']</value>
      <webElementGuid>d1e02789-60e2-4154-9b63-a619a9fcdde1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>748ebb18-72dd-4793-8bc4-f04d2b135dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn-create-entry']</value>
      <webElementGuid>111e40c9-e3c7-4414-bf76-b9f698384873</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
