<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Find</name>
   <tag></tag>
   <elementGuidId>1260416b-98b0-4421-a3ce-9419a243b746</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.k-item.btn-group-link.k-state-default.k-state-hover > a.k-link.k-menu-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Menu']/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>76b5868a-3cd4-4ce2-98fa-520b6ad99e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link k-menu-link</value>
      <webElementGuid>a50b6d12-6610-4448-a227-0b0b2c5239c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ToFindList</value>
      <webElementGuid>e59b07fc-7cf6-4d0b-b8a9-dab466764cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find</value>
      <webElementGuid>71c4db87-120a-4d66-983c-8e2ee29e3d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Menu&quot;)/li[@class=&quot;k-item btn-group-link k-state-default k-state-hover&quot;]/a[@class=&quot;k-link k-menu-link&quot;]</value>
      <webElementGuid>69595f02-6d08-46ce-8dcd-c36202914927</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Menu']/li[3]/a</value>
      <webElementGuid>61a3f89d-12c5-4a0e-b5c3-f7c69f68f930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Find')]</value>
      <webElementGuid>33c71487-3ce0-4fd4-85b2-8d0f247db2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset'])[1]/following::a[1]</value>
      <webElementGuid>bd5ab091-a042-41ea-8320-a8d861b04e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[2]</value>
      <webElementGuid>5b764daf-a662-4dd2-99cc-f491ae93d678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disposable Order'])[1]/preceding::a[1]</value>
      <webElementGuid>e2857c35-e25e-4448-83f0-b992e93ded52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requests'])[1]/preceding::a[2]</value>
      <webElementGuid>c056bbce-ce1f-4fdd-b45c-b132fddd2549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Find']/parent::*</value>
      <webElementGuid>a4692d5a-373a-4436-85e8-7b366d51c2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ToFindList')]</value>
      <webElementGuid>1d52268c-c8ef-46f6-b032-f996a47e266c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>65c838a6-189f-49eb-a9fe-542649996734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ToFindList' and (text() = 'Find' or . = 'Find')]</value>
      <webElementGuid>c9f97926-96a6-4fc9-bde7-e009b1da2078</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
