<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New Name_txtName</name>
   <tag></tag>
   <elementGuidId>2383e308-0008-4fee-ae59-8a00ecaf88c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5d3e101-22c6-448f-b1ed-46ed38807ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>54013516-8494-416d-8a9f-85d5d87988fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtName</value>
      <webElementGuid>0055e623-cfb7-488f-b8b8-1808ad2ea3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>eb0c95f8-4276-4d0f-9d34-3a24f9068c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>onToFindListNewName()</value>
      <webElementGuid>498b7af8-e412-4089-a9f6-a3b43e687597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtName&quot;)</value>
      <webElementGuid>2d7ab0ef-1b2d-44c7-aa9f-7d3e93cf9982</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtName']</value>
      <webElementGuid>0c4ede2c-1bd7-4d47-af60-f9f43b069e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='window']/input</value>
      <webElementGuid>ec084c73-4c07-4d64-997e-aecab9c04a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[44]/div[2]/input</value>
      <webElementGuid>15fc928f-67a9-4f37-b0e9-4c7e98eea18f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtName']</value>
      <webElementGuid>d9322a91-b457-43ab-b2fc-4546a5996796</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
