<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please select assets by checking the _2c57b4</name>
   <tag></tag>
   <elementGuidId>8a5b7e41-7ca4-4b0e-8ec8-1afc1501c867</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#window > input.btn.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Create / Add To List']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9113cf7f-cf3f-4c99-ae7b-d0e14e0e2759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5251fcd2-bc81-4d54-abac-d0bcfc6cf623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Create / Add To List</value>
      <webElementGuid>a79054f9-164d-41f2-b67f-53c3032ce001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>61f80216-d8d3-440a-9962-c68dc9e51313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addToFindList()</value>
      <webElementGuid>f4485e75-ba83-4f3d-8596-ba451f7af686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;window&quot;)/input[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>8b02ad37-8715-4ba5-b030-c87ff38075a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Create / Add To List']</value>
      <webElementGuid>74e11feb-2a77-42e0-a85f-0d24106f29c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='window']/input[2]</value>
      <webElementGuid>8dbc9c3b-feed-4e13-89e6-2200007d86c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[44]/div[2]/input[2]</value>
      <webElementGuid>6c03a6dd-67f4-4e58-937f-3a1335dda3b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>631ac8a8-ea56-444b-b2c6-17a8ec0fc024</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
