<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Is equal to_k-input</name>
   <tag></tag>
   <elementGuidId>884fdf18-7ee1-46d4-82be-f1e8c54677ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-widget.k-autocomplete.k-autocomplete-clearable.k-state-default.k-state-hover.k-state-focused > input.k-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ea2fe14-24c2-441f-9176-628d0ce132ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: value</value>
      <webElementGuid>74363d91-b8b0-4bb7-bbff-90497dd48568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Barcode</value>
      <webElementGuid>91481926-e650-4320-afb7-0a30ebdb82b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Barcode</value>
      <webElementGuid>5f652a30-e06a-4b06-863d-2d17de80abdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>autocomplete</value>
      <webElementGuid>b222c937-7a2d-48ac-b0af-6baabea5cafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text-field</name>
      <type>Main</type>
      <value>Barcode</value>
      <webElementGuid>aec1daf7-bdaf-4e23-9b87-f390dd524c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-filter</name>
      <type>Main</type>
      <value>startswith</value>
      <webElementGuid>9addfe55-d8cc-45c0-b125-a71898d4d74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-delay</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>cb3d0a3b-1004-4881-8708-bbc109c577b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min-length</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e1e39cf6-a213-4002-9185-7acfbea14517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value-primitive</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>468fe6d3-a73a-488e-80bd-3519c9b24e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3321a5aa-84d4-4ce9-a6fc-a97e573ae138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>924d9983-84e8-4ad4-927c-42200d2e5650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>422e187b-394f-44eb-a53f-21b59cc1f0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>052e9463-746e-4859-b567-e5da012a8b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>79ccdd39-6f1f-45a8-9ff2-d6260b02b85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dcf165c3-a0dc-4861-a529-f854abb37759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d205ae0a-9861-4a8e-80db-05dff6504906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>b8b9c6ec-16fa-4b6e-8fb5-9737cec4d7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>871b9ffb-31dd-4684-b11a-5b23ae43d01e_listbox</value>
      <webElementGuid>8eafcaf9-f0af-4fb5-b1a6-3ecda66f3934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid&quot;)/div[@class=&quot;k-grid-header&quot;]/div[@class=&quot;k-grid-header-wrap k-auto-scrollable&quot;]/table[1]/thead[1]/tr[@class=&quot;k-filter-row&quot;]/th[3]/span[@class=&quot;k-filtercell&quot;]/span[1]/span[@class=&quot;k-widget k-autocomplete k-autocomplete-clearable k-state-default k-state-hover k-state-focused&quot;]/input[@class=&quot;k-input&quot;]</value>
      <webElementGuid>b709e115-c76d-4701-ae52-fb6883d952f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>cf6325c3-6b0a-4333-b0f4-f4df90b2d4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grid']/div/div/table/thead/tr[2]/th[3]/span/span/span/input</value>
      <webElementGuid>73e82c93-24ab-4ad8-8215-e61837fcaa56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/span/span/span/input</value>
      <webElementGuid>f6c5a718-1890-4b74-9e21-1ee0bb892eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Barcode' and @type = 'text']</value>
      <webElementGuid>888beea1-79cc-4109-85d4-949f677a5032</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
