<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Download Template_btn-create-entry</name>
   <tag></tag>
   <elementGuidId>080556fa-0a8f-46fb-8dae-25858d687b60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-create-entry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn-create-entry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3823a1c6-f2b5-4482-a95a-e3deed02457c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b7efdf26-1123-495b-8a2e-fb596d2fbec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-create-entry</value>
      <webElementGuid>137048ef-34aa-4181-aa07-7691a8187b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add Asset</value>
      <webElementGuid>b63f187c-e960-42b3-a9ed-375ced10d702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary</value>
      <webElementGuid>04d9274d-f0fb-4dcb-ba12-0045cbf0cfbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>attr-add-url</name>
      <type>Main</type>
      <value>/Asset/Add</value>
      <webElementGuid>fa2822f9-7a31-404d-9854-adf95ba779d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-create-entry&quot;)</value>
      <webElementGuid>ed738c69-1c43-4330-bcee-7c49563a6d6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn-create-entry']</value>
      <webElementGuid>df60c571-cc86-4521-a324-ad3d5d63f45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>83fb1962-2f2b-4dc4-a0b6-6f38431fb635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn-create-entry']</value>
      <webElementGuid>45c74d18-7772-44c3-8428-26d0f1ec30da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
