<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Is equal to_k-icon k-clear-value k-i-close</name>
   <tag></tag>
   <elementGuidId>d278d330-59b0-443a-b827-91af1897407f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-widget.k-autocomplete.k-autocomplete-clearable.k-state-default.k-state-border-down.k-state-hover > span.k-icon.k-clear-value.k-i-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='grid']/div/div/table/thead/tr[2]/th[3]/span/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2b9a9556-b45e-42c2-a74d-5c52d21259d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>8bba02b9-3192-456c-a5dc-28e8bea6306d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-clear-value k-i-close</value>
      <webElementGuid>dbe8159f-fcf9-433e-b80e-eb4228cf08c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>clear</value>
      <webElementGuid>0249536b-dd4d-42c6-ac2c-673a79647c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00498726-3c82-4dcb-8873-b3dd02eb8193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6b0d59d0-98c1-4f47-9207-8cc476e40d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid&quot;)/div[@class=&quot;k-grid-header&quot;]/div[@class=&quot;k-grid-header-wrap k-auto-scrollable&quot;]/table[1]/thead[1]/tr[@class=&quot;k-filter-row&quot;]/th[3]/span[@class=&quot;k-filtercell&quot;]/span[1]/span[@class=&quot;k-widget k-autocomplete k-autocomplete-clearable k-state-default k-state-border-down k-state-hover&quot;]/span[@class=&quot;k-icon k-clear-value k-i-close&quot;]</value>
      <webElementGuid>32d08454-0a94-4fb4-912b-980f16881779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grid']/div/div/table/thead/tr[2]/th[3]/span/span/span/span</value>
      <webElementGuid>fb7e4a7f-7e29-42a3-9b4b-db40f9c43296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/span/span/span/span</value>
      <webElementGuid>07a44d74-71b3-4bf4-bd01-2d6b7ebe74cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'clear']</value>
      <webElementGuid>b9495e1e-1ac0-46c6-bf32-9a9165c2df7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
