<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Is equal to_k-icon k-i-expand</name>
   <tag></tag>
   <elementGuidId>e02bbbd0-77fd-47e3-9721-31215d08e310</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.k-icon.k-i-expand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='grid']/div[2]/table/tbody/tr/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5b882160-c991-4ab6-9604-8ca13ff8f290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-expand</value>
      <webElementGuid>16bfe158-8e98-40ab-97d9-9bc47b19be01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>75f95ebf-bbe0-45e5-af17-4b532a8c6f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Expand</value>
      <webElementGuid>799a66bd-4770-4fe1-bdbe-d439486f9250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>847a75d0-9159-499e-8839-4caf151fd8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid&quot;)/div[@class=&quot;k-grid-content k-auto-scrollable&quot;]/table[1]/tbody[1]/tr[@class=&quot;k-master-row&quot;]/td[@class=&quot;k-hierarchy-cell&quot;]/a[@class=&quot;k-icon k-i-expand&quot;]</value>
      <webElementGuid>36abeef2-60d1-4fd1-ac67-cd3778e84c8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grid']/div[2]/table/tbody/tr/td/a</value>
      <webElementGuid>71b3f64e-d2b9-40ba-b330-ac95e0d3f75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[7]</value>
      <webElementGuid>fbfc75ba-9725-4791-9571-a01d602c7523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>7028ec7a-b4b0-49ec-bbd9-28dfebb64f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>732e6dce-83af-44a9-bfaf-a4d3879c9117</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
