<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Asset</name>
   <tag></tag>
   <elementGuidId>b2ceeb6a-ebc7-4c79-93de-4fdbe806f358</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.k-item.btn-group-link.k-state-default.k-state-hover > a.k-link.k-menu-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Menu']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6a791741-377a-4abe-8343-cc5ecfeb0ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link k-menu-link</value>
      <webElementGuid>cab2edaf-fa9c-4751-bbab-21bf87158d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Asset</value>
      <webElementGuid>bdd5e8b9-fc90-472c-89f7-29df7ec31671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Asset</value>
      <webElementGuid>0381928c-553c-4d36-a2b5-a95cb8f8538b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Menu&quot;)/li[@class=&quot;k-item btn-group-link k-state-default k-state-hover&quot;]/a[@class=&quot;k-link k-menu-link&quot;]</value>
      <webElementGuid>e5fd573c-7bb2-41f4-8388-e9c1c2e8b254</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Menu']/li[2]/a</value>
      <webElementGuid>850048f9-85b2-4881-bfb6-35c1fd6d342b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Asset')]</value>
      <webElementGuid>79e46379-87cd-441e-a13a-019579451d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[1]</value>
      <webElementGuid>cd10bda9-d6ec-405b-b4b6-4851876ca61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find'])[1]/preceding::a[1]</value>
      <webElementGuid>4720a7e5-0e12-4273-a532-5f71300d8f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disposable Order'])[1]/preceding::a[2]</value>
      <webElementGuid>e05866c1-3fb9-443b-83ac-c16ff9d40ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Asset']/parent::*</value>
      <webElementGuid>447329df-bb19-41fe-a4ca-e63c495146a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Asset')]</value>
      <webElementGuid>b42c7c6b-6176-4405-a0dd-f02a4a548345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>3fb41ac7-c37d-4a02-87ca-c667fd0a4d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Asset' and (text() = 'Asset' or . = 'Asset')]</value>
      <webElementGuid>83ebfbc3-dffa-4965-a9b6-2e2a050f4662</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
