<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Asset</name>
   <tag></tag>
   <elementGuidId>5986272a-1e24-45ba-9f3f-47aa70f07232</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Menu_mn_active > a.k-link.k-menu-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='Menu_mn_active']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6af7d431-0aa9-4cca-854c-83f03412d817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link k-menu-link</value>
      <webElementGuid>41950df6-4f32-4679-bd1c-6d20338965b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Asset</value>
      <webElementGuid>f8967e2f-93ca-46ac-90fc-7f1421a9a075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Asset</value>
      <webElementGuid>5d75f42c-cdb1-44a9-afd2-7a0bedc7a3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Menu_mn_active&quot;)/a[@class=&quot;k-link k-menu-link&quot;]</value>
      <webElementGuid>40f074f6-fb6d-44e6-9dfc-25e4579e7191</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='Menu_mn_active']/a</value>
      <webElementGuid>37d60525-8d8c-43e0-9b79-8c190a41fa23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Asset')]</value>
      <webElementGuid>83fd5008-cd5b-47ab-af50-bc2f261a06ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[1]</value>
      <webElementGuid>13a1bdd1-95ab-4818-8898-2ed17b10bb1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find'])[1]/preceding::a[1]</value>
      <webElementGuid>f1688025-714e-48d2-b968-9e1b383cbb49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disposable Order'])[1]/preceding::a[2]</value>
      <webElementGuid>a13b3abf-db43-4b86-98e0-567ed4ab78f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Asset']/parent::*</value>
      <webElementGuid>fb4dc2c9-8b84-41a2-9adc-e184dddc2df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Asset')]</value>
      <webElementGuid>8e9383ca-c279-4138-9b09-a84c6f1d6776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>2b09e6bb-3b0d-4051-b36e-ac23d279130c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Asset' and (text() = 'Asset' or . = 'Asset')]</value>
      <webElementGuid>13549979-c2a9-4820-8414-baeb2f33a246</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
