<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Export_btn-create-entry</name>
   <tag></tag>
   <elementGuidId>d1ad13f3-5b78-422e-9ab0-61331b85f7e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-create-entry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn-create-entry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2396e86-16e4-4c6f-a9b9-d4e7e68d54e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2a944a2a-5b2f-43be-93c7-e6f1dffcce10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-create-entry</value>
      <webElementGuid>591b80b2-d8a7-4739-8e61-254e20299197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add Asset</value>
      <webElementGuid>6952a587-3ed3-4406-88c9-667e0801a706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary</value>
      <webElementGuid>185247e1-5deb-4622-9af7-d89231170572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>attr-add-url</name>
      <type>Main</type>
      <value>/Asset/Add</value>
      <webElementGuid>752af704-7b94-4b38-a20a-b8c2454bbad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-create-entry&quot;)</value>
      <webElementGuid>341645fd-55e1-4f30-97e5-ec03f16bf14b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn-create-entry']</value>
      <webElementGuid>5117035d-2fd5-447f-b8c4-47c7b3674cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>b89867e0-20e0-455e-9aa7-8a32c0880335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn-create-entry']</value>
      <webElementGuid>e7e89bb6-913a-4aaf-b948-7990707ce709</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
