<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Barcode_Barcode</name>
   <tag></tag>
   <elementGuidId>08e87d15-6db2-4b7b-b866-5f8da9999f74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Barcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Barcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7c72ac0-b766-48c3-a6a6-35c3903ba7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>medequip-input w-100 k-invalid</value>
      <webElementGuid>c49dc1bc-c711-4fe1-963f-d99a8fd228f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>3c7d9091-545e-43c1-94a8-e175d5ad961e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d5c8052-6799-4558-bc80-0f01426c68f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>134cfa8d-fc6e-41c5-ae0e-1f50c5fbf4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Invalid Barcode- alphanumeric allowed.</value>
      <webElementGuid>70752cf7-3733-4e6a-9268-8a94d26eae9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>[A-Za-z0-9]+</value>
      <webElementGuid>49b83191-7ee1-493f-ada8-4421f1b00ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Required field</value>
      <webElementGuid>b768e255-fec2-4b87-9c33-fc95418b9f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Barcode</value>
      <webElementGuid>dc2a1a39-9f55-4e78-8a89-61300ba41be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Barcode</value>
      <webElementGuid>2116e5e5-8bad-410e-9436-25e2c93f3f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Barcode&quot;)</value>
      <webElementGuid>ab4235ee-06c0-4476-82a5-7fbd5d30dc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>632d2623-3d8c-4346-9cae-f9a371c36833</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Barcode']</value>
      <webElementGuid>4072ec8d-bc68-4144-80cc-51d992567dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-add-entry']/div[2]/div[3]/div/div/div[2]/input</value>
      <webElementGuid>74c11cf9-4816-44e9-8093-d382f1ef9c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/input</value>
      <webElementGuid>0c9fc82d-38ce-45c8-a8d8-c3edc66af1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Barcode' and @name = 'Barcode']</value>
      <webElementGuid>706ea62b-80be-4208-a3e9-c9e6812b02ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
