<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Serial Number_SerialNumber</name>
   <tag></tag>
   <elementGuidId>7fa88a6f-c972-4885-a526-57117341d049</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SerialNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SerialNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae0d1473-37f3-463e-9323-545a226430ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>medequip-input w-100 k-invalid</value>
      <webElementGuid>b545108d-9162-4480-8814-27024f90b74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>a0ed428d-3517-44ef-83ca-2c80dde4b5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dadbb220-9cf4-4329-ac6d-e343329c2b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>43052785-c9b9-4e04-94b8-7dc2e2b8e21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field SerialNumber must be a string or array type with a maximum length of '50'.</value>
      <webElementGuid>0853d174-a7fa-4157-8c97-dad5935ebed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>97e0ac9e-f6b9-49e4-92c2-889e4212c899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Invalid SerialNumber- alphanumeric allowed.</value>
      <webElementGuid>b51fbeb4-c73f-4846-813c-f7b37e20dc89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>[A-Za-z0-9]+</value>
      <webElementGuid>d90d2493-98f9-4f0a-9acb-e06f4564107b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Required field</value>
      <webElementGuid>d9119596-d82d-4b36-8fe0-eb18bbec2552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SerialNumber</value>
      <webElementGuid>0194cc26-be69-469e-8a91-97a7245b4f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SerialNumber</value>
      <webElementGuid>a06f291e-66ec-462a-b029-128e889704c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SerialNumber&quot;)</value>
      <webElementGuid>451b380d-3208-4ac2-9c45-9dafb52b1075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>87935b84-9407-4d95-b8e6-b3ab1d8431f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SerialNumber']</value>
      <webElementGuid>a09c366d-b77d-4a11-b089-9e84fd7c1b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-add-entry']/div[2]/div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>d4d94367-6b8b-4f62-a050-3eee38782a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>3d248838-6d1f-4b4c-9571-d92347860508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'SerialNumber' and @name = 'SerialNumber']</value>
      <webElementGuid>227b6324-1aaa-42e0-8722-be13826071ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
