<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_--Please Select--_k-icon k-i-arrow-60-down</name>
   <tag></tag>
   <elementGuidId>20da5b82-261f-434d-b7d3-4c01db387d56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-dropdown-wrap.k-state-default.k-invalid.k-state-hover.k-state-focused > span.k-select > span.k-icon.k-i-arrow-60-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form-add-entry']/div[2]/div[5]/div[2]/span/span/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0e8b813f-e29c-4875-a054-21a7a64dc052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-arrow-60-down</value>
      <webElementGuid>4ea77eb0-be20-4840-9f34-3e9123eb2755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-add-entry&quot;)/div[@class=&quot;modal-body added-scroll&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-sm-6&quot;]/span[@class=&quot;k-widget k-dropdown form-control medequip-select&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-invalid k-state-hover k-state-focused&quot;]/span[@class=&quot;k-select&quot;]/span[@class=&quot;k-icon k-i-arrow-60-down&quot;]</value>
      <webElementGuid>5e28133b-ff67-448c-97f3-b01129fc74e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-add-entry']/div[2]/div[5]/div[2]/span/span/span[2]/span</value>
      <webElementGuid>b8bffb53-f210-4ef4-871e-a835dea21c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/span/span/span[2]/span</value>
      <webElementGuid>ca29ca24-0ddc-490f-aef4-a62b2469b838</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
