<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Export_btn-create-entry</name>
   <tag></tag>
   <elementGuidId>47739e16-f319-42f3-9a30-f8a1d57a3115</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-create-entry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn-create-entry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f7bb3d6-0adb-47a0-a62f-2226e68004a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3a57f45-818b-4bdf-9e6f-39fe93b7cc12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-create-entry</value>
      <webElementGuid>e4d8be9c-cb11-46b6-b0e8-0bffc9e82ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add PAR Level</value>
      <webElementGuid>f26e56cd-8848-48b6-99a4-512d3d7483fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary float-right</value>
      <webElementGuid>972443a6-c4b2-4f12-b933-027ba7d16368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>attr-add-url</name>
      <type>Main</type>
      <value>/ParLevel/Add</value>
      <webElementGuid>2f4e82f3-56c9-4c63-83d2-692aa831c433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-create-entry&quot;)</value>
      <webElementGuid>7774c902-65d5-49a6-a427-36ae47c04bff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn-create-entry']</value>
      <webElementGuid>34acda4e-4e23-4ca8-acd2-91c291689ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>94831be9-f4a3-41a6-ad5f-678fddf8e778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btn-create-entry']</value>
      <webElementGuid>51c8f879-b86d-4a04-8f08-4c04e430fd7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
